trame: # Default app under /index.html
  www_modules:
    - vera_core.module
  cmd:
    - /opt/paraview/bin/pvpython
    - --mesa
    - -m
    - paraview.apps.trame
    - --trame-app
    - vera_core.app
    - --data
    - /opt/vera-core/data.h5
    - --host
    - ${host}
    - --port
    - ${port}
    - --authKey
    - ${secret}
    - --server
